#!/bin/bash


# Update OS
apt-get update && apt dist-upgrade;

# Install some extensions, essential os tools, personalize gnome shell
sudo apt install -y build-essential git net-tools gnome-shell gnome-shell-extension-appindicator gnome-shell-extension-gsconnect gnome-shell-extension-gsconnect-browsers gnome-shell-extension-manager gnome-shell-extensions gdb wine wine64 curl binwalk hexcurse cppcheck clang clang-tools cargo afl++ wireshark snap;
