#!/bin/bash



cd /tmp;
wget https://minecraft.azureedge.net/bin-linux/bedrock-server-1.20.80.05.zip;

sudo su << 'EOF'

	unzip -d /usr/local/games/minecraft_server/bedrock ./bedrock-server-1.20.80.05.zip
	chown -R minecraft: /usr/local/games/minecraft_server/

EOF