#!/bin/bash

# Credit for a portion of the script goes to [Mincraft-Server-Tutorial](https://www.cherryservers.com/blog/minecraft-server-ubuntu) with some adjustments made by myself

# Prepare system for minecraft server
# Temporarily switch to root


# Create Java Server Home Folder
sudo su << 'EOF'
	# Create a minecraft user
	useradd -r -U -d /usr/local/games/minecraft_server/ -s /usr/sbin/nologin minecraft;

	# Create Minecraft Java Server Folder
	mkdir -p /usr/local/games/minecraft_server/java;

	# Set permissions
	chown -R minecraft: /usr/local/games/minecraft_server/;

	firewall-cmd --permanent --zone=public --add-port 25565/tcp;
	firewall-cmd --permanent --zone=public --add-port 25565/udp;
	firewall-cmd --reload;
	exit
	

EOF



# Switch to minecraft user and begin installation

sudo su - minecraft -s /bin/bash << 'FOE'

	# Download Minecraft Java
	cd /usr/local/games/minecraft_server/java;
	wget https://piston-data.mojang.com/v1/objects/79493072f65e17243fd36a699c9a96b4381feb91/server.jar -O ./server.jar;

	# Init Java
	java -Xmx1024M -Xms1024M -jar ./server.jar nogui &

	sed -i 's/\bfalse\b/TRUE/' ./eula.txt;

FOE


sudo su - minecraft -s /bin/bash << 'EOF'

	cd /usr/local/games/minecraft_server/java;

	# Accept EULA
	sed -i 's/\bfalse\b/TRUE/' ./eula.txt;

	# Init Again
	java -Xmx1024M -Xms1024M -jar ./server.jar nogui &

	# Launch the Server
	screen -S mc_java_server -dm java -Xmx1024M -Xms1024M -jar ./server.jar nogui & 
EOF



