#!/bin/bash

# Credit for most of this portion of the script goes to [Mincraft-Server-Tutorial](https://www.cherryservers.com/blog/minecraft-server-ubuntu)

# Prepare system for minecraft server
# Temporarily switch to root

sudo su << 'EOF'

	# Create a minecraft user
	useradd -r -U -d /usr/local/games/minecraft_server/ -s /usr/sbin/nologin minecraft;

	# Create Minecraft Java Server Folder
	mkdir -p /usr/local/dames/minecraft_server/Java;

	# Set permissions
	chown -R minecraft: /usr/local/games/minecraft_server/;
EOF

# Switch to minecraft user and begin installation

sudo su -minecraft -s /bin/bash