#!/bin/bash

# Create Minecraft Usr
wget https://raw.githubusercontent.com/AgentAstro/Scripting-Final-Temp/main/create-minecraft-usr -O ./create-minecraft-usr;
chmod +x ./create-minecraft-usr;
./create-minecraft-usr;


# Download Bedrock Server
cd /tmp;
wget https://minecraft.azureedge.net/bin-linux/bedrock-server-1.20.80.05.zip;


# Extract and fix permissions
sudo su << 'EOF'

	unzip -d /usr/local/games/minecraft_server/bedrock ./bedrock-server-1.20.80.05.zip
	chown -R minecraft: /usr/local/games/minecraft_server/

EOF