#!/bin/bash

# Credit for a portion of the script goes to [Mincraft-Server-Tutorial](https://www.cherryservers.com/blog/minecraft-server-ubuntu) with some adjustments made by myself

# Prepare system for minecraft server
# Temporarily switch to root


# Create Java Server Home Folder
sudo su << 'EOF'

	apt install openjdk-21-jre-headless curl wget grep

	# Create a minecraft user
	useradd -r -U -d /usr/local/games/minecraft_server/ -s /usr/sbin/nologin minecraft;

	# Create Minecraft Java Server Folder
	mkdir -p /usr/local/games/minecraft_server/java;

	# Set permissions
	chown -R minecraft: /usr/local/games/minecraft_server/;

	firewall-cmd --permanent --zone=public --add-port 25565/tcp;
	firewall-cmd --permanent --zone=public --add-port 25565/udp;
	firewall-cmd --reload;
	exit
	

EOF



# Switch to minecraft user and begin installation

sudo su - minecraft -s /bin/bash << 'FOE'

	DOWNLOAD_URL=$(curl -H "Accept-Encoding: identity" -H "Accept-Language: en" -s -L -A "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; JAVA-UPDATER)" https://www.minecraft.net/en-us/download/server | grep -o 'https.*server\.jar');

	# Download Minecraft Java
	cd /usr/local/games/minecraft_server/java;
	wget -U "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; JAVA-UPDATER)" $DOWNLOAD_URL -O ./server.jar;

	# Init Java
	java -Xmx1024M -Xms1024M -jar ./server.jar nogui &

	sed -i 's/\bfalse\b/TRUE/' ./eula.txt;

FOE


sudo su - minecraft -s /bin/bash << 'EOF'

	cd /usr/local/games/minecraft_server/java;

	# Accept EULA
	sed -i 's/\bfalse\b/TRUE/' ./eula.txt;

	# Init Again
	java -Xmx1024M -Xms1024M -jar ./server.jar nogui &

	# Launch the Server
	screen -S mc_java_server -dm java -Xmx1024M -Xms1024M -jar ./server.jar nogui & 
EOF



