#!/bin/bash


# Update OS and Install helpful applications/programs

sudo su << 'EOF'

	apt-get update && apt --fix-broken install -y && apt dist-upgrade -y;

	# Install some extensions, essential os tools, personalize gnome shell

	apt install -y build-essential git net-tools gnome-shell gnome-tweaks gnome-shell-extension-appindicator gnome-shell-extension-gsconnect gnome-shell-extension-gsconnect-browsers gnome-shell-extension-manager gnome-shell-extensions gdb wine wine64 curl binwalk hexcurse cppcheck clang clang-tools cargo afl++ snap htop vim python3 python3-pip openjdk-21-jre-headless screen firewalld g++ unzip;
	apt autoremove;

	snap install code --classic -y;
EOF

# Set bash aliases in your home directory
wget -q https://raw.githubusercontent.com/AgentAstro/Scripting-Final-Temp/main/.bash_aliases -O ~/.bash_aliases;
source ~/.bash_aliases;

# Ask the user if they want to install minecraft
while true; do
	read -p "Do you want to install Minecraft Server Java? " yn
	case $yn in 
		[Yy]* ) wget https://raw.githubusercontent.com/AgentAstro/Scripting-Final-Temp/main/setup-minecraft-java -O ./setup-minecraft-java; chmod +x ./setup-minecraft-java; sudo ./setup-minecraft-java; break;;
		[Nn]* ) break;;
		* ) echo "Please choose yes or no.";;
	esac
done;

# while true; do
# 	read -p "Do you want to install Minecraft Server Bedrock? " yn
# 	case $yn in 
# 		[Yy]* ) wget https://raw.githubusercontent.com/AgentAstro/Scripting-Final-Temp/main/setup-minecraft-java -O ./setup-minecraft-java; chmod +x ./setup-minecraft-java; sudo ./setup-minecraft-bed; break;;
# 		[Nn]* ) break;;
# 		* ) echo "Please choose yes or no.";;
# 	esac
# done

