#!/bin/bash

# Update OS
sudo apt-get update && sudo apt dist-upgrade -y;

# Install some extensions, essential os tools, personalize gnome shell
sudo apt install -y build-essential git net-tools gnome-shell gnome-shell-extension-appindicator gnome-shell-extension-gsconnect gnome-shell-extension-gsconnect-browsers gnome-shell-extension-manager gnome-shell-extensions gdb wine wine64 curl binwalk hexcurse cppcheck clang clang-tools cargo afl++ wireshark snap vim python3 python3-pip;

# Set bash aliases in your home directory
wget -q https://raw.githubusercontent.com/AgentAstro/Scripting-Final-Temp/main/.bash_aliases -O ~/bash_aliases;
source ~/.bash_aliases;

# Install vscode
sudo snap install code --classic;