#!/bin/bash


# Update OS

sudo su << 'EOF'

	apt-get update && apt --fix-broken install -y && apt dist-upgrade -y;

	# Install some extensions, essential os tools, personalize gnome shell

	apt install -y build-essential git net-tools gnome-shell gnome-tweaks gnome-shell-extension-appindicator gnome-shell-extension-gsconnect gnome-shell-extension-gsconnect-browsers gnome-shell-extension-manager gnome-shell-extensions gdb wine wine64 curl binwalk hexcurse cppcheck clang clang-tools cargo afl++ snap htop vim python3 python3-pip default-jre-headless;

	snap install code --classic
EOF

# Set bash aliases in your home directory
wget -q https://raw.githubusercontent.com/AgentAstro/Scripting-Final-Temp/main/.bash_aliases -O ~/.bash_aliases;

source ~/.bash_aliases;

# Install vscode

# Next I set up a minecraft server and run it

